name: Go
permissions: write-all

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:


  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - run: go version
    
    
    - name: Test
      run: go test -v ./...
      
    - name: Build
      run: go build -v ./...
       
    - name: Upload artifacts linux_amd64
      uses: actions/upload-artifact@v2
      with:
        name: go-http-proxy
        path: ./go-http-proxy

#     - uses: actions/checkout@master
#     - name: Create a Release
#       uses: elgohr/Github-Release-Action@master
  
#       env:
#         GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
#       with:
#         args: MyReleaseMessage
      
      
